project 'TrueReview.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrueReview' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8.0'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'ObjectMapper', '~> 3.4'
  
  # Pods for TrueReview

end
